name: Deploy

on:
  release:
    types: [published]

jobs:
  wheels:
    runs-on: ${{ matrix.build-platform[0] }}
    strategy:
      fail-fast: false
      matrix:
        build-platform:
          - [ubuntu-20.04, manylinux_x86_64]
          - [windows-2019, win_amd64]
        python-version: ["cp37", "cp38", "cp39", "cp310"]

    env:
      IS_32_BIT: ${{ matrix.build-platform[1] == 'win32' }}

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.3.1
        env:
          CIBW_BUILD: ${{ matrix.python-version }}-${{ matrix.build-platform[1] }}

      - uses: actions/upload-artifact@v2
        with:
          name: python-package-distributions
          path: ./wheelhouse/*.whl

  deploy-wheels:
    runs-on: ubuntu-latest
    needs:
      - wheels

    steps:
      - uses: actions/download-artifact@v2
        with:
          name: python-package-distributions
          path: ./wheelhouse
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          packages_dir: wheelhouse
          skip_existing: true

  sdist:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.release.tag_name }}
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
      - name: Build package
        run: python -m build -s
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
